Default path for the configuration file
hanford/add-component pull request #8
Opened 2018-01-19 13:27 UTC by varya

2018-01-23 04:05 UTC, hanford requested changes

2018-01-23 04:05 UTC, hanford commented on README.md
> +$ add-react-component --config congifs/addcomponent-config.js Example
i think you mean configs

2018-01-23 13:21 UTC, varya commented on README.md
> +$ add-react-component --config congifs/addcomponent-config.js Example
My bad :-) Fixed.

2018-01-23 19:33 UTC, hanford commented
dope!

2018-01-23 19:35 UTC, merged

2018-01-23 19:37 UTC, hanford commented
both of your changes are live in v2.5.0! Thanks again 🤗

2018-01-24 09:47 UTC, varya commented
🎉 Thanks!